# Generated by Django 2.2.17 on 2021-01-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(default='machine/default.png', upload_to='machine'),
        ),
        migrations.AlterField(
            model_name='production',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
