# Generated by Django 2.2.17 on 2021-01-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210121_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.BinaryField()),
            ],
        ),
    ]
