# Generated by Django 2.2.17 on 2021-01-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_production_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='machinetime',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
