# Generated by Django 2.2.17 on 2021-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20210122_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finnish',
            field=models.BooleanField(default=False),
        ),
    ]
