# Generated by Django 2.2.17 on 2021-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_order_finnish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(default='machine/default.jpg', upload_to='machine'),
        ),
    ]
