# Generated by Django 2.2.17 on 2021-01-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210121_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='domain',
            field=models.SlugField(default='sdfsfsfsfsf', unique=True),
        ),
    ]
