# Generated by Django 2.2.17 on 2021-01-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_mlmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='created',
        ),
    ]
