# Generated by Django 2.2.17 on 2021-01-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
